### ISSUE TITLE
Incorrect C code was generated

### ISSUE THREAD

**Issue by PavelAndrianov** [tautschnig/fshell#1]
Hi!

I looked at problems with witness validation with fshell.
In a large number of benchmarks it generates the following dummy function:
```
void *__VERIFIER_nondet_pointer(void){ 
   static unsigned idx = 0;  
   void retval1[1] = { 0 };  
   switch (__fshell2__tc_selector) {  
     case 0: return retval1[idx++];  
   }  
}
```
Then a compiler fails with 
> error: declaration of ‘retval1’ as array of voids

Seems, this is a bug.

**Comment by tautschnig** [comment]
I'm afraid you've picked the wrong project to report this to, you'd likely want fshell-w2t.

**Comment by tautschnig** [comment]
(And I've just fixed it there.)

**Comment by PavelAndrianov** [comment]
Thanks!
